package com.king2.commons.mapper;

import com.king2.commons.pojo.K2FeedbackReply;
import com.king2.commons.pojo.K2FeedbackReplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface K2FeedbackReplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table k2_feedback_reply
     *
     * @mbggenerated Sat Aug 31 14:11:52 CST 2019
     */
    int countByExample(K2FeedbackReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table k2_feedback_reply
     *
     * @mbggenerated Sat Aug 31 14:11:52 CST 2019
     */
    int deleteByExample(K2FeedbackReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table k2_feedback_reply
     *
     * @mbggenerated Sat Aug 31 14:11:52 CST 2019
     */
    int deleteByPrimaryKey(Integer replyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table k2_feedback_reply
     *
     * @mbggenerated Sat Aug 31 14:11:52 CST 2019
     */
    int insert(K2FeedbackReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table k2_feedback_reply
     *
     * @mbggenerated Sat Aug 31 14:11:52 CST 2019
     */
    int insertSelective(K2FeedbackReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table k2_feedback_reply
     *
     * @mbggenerated Sat Aug 31 14:11:52 CST 2019
     */
    List<K2FeedbackReply> selectByExampleWithBLOBs(K2FeedbackReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table k2_feedback_reply
     *
     * @mbggenerated Sat Aug 31 14:11:52 CST 2019
     */
    List<K2FeedbackReply> selectByExample(K2FeedbackReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table k2_feedback_reply
     *
     * @mbggenerated Sat Aug 31 14:11:52 CST 2019
     */
    K2FeedbackReply selectByPrimaryKey(Integer replyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table k2_feedback_reply
     *
     * @mbggenerated Sat Aug 31 14:11:52 CST 2019
     */
    int updateByExampleSelective(@Param("record") K2FeedbackReply record, @Param("example") K2FeedbackReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table k2_feedback_reply
     *
     * @mbggenerated Sat Aug 31 14:11:52 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") K2FeedbackReply record, @Param("example") K2FeedbackReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table k2_feedback_reply
     *
     * @mbggenerated Sat Aug 31 14:11:52 CST 2019
     */
    int updateByExample(@Param("record") K2FeedbackReply record, @Param("example") K2FeedbackReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table k2_feedback_reply
     *
     * @mbggenerated Sat Aug 31 14:11:52 CST 2019
     */
    int updateByPrimaryKeySelective(K2FeedbackReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table k2_feedback_reply
     *
     * @mbggenerated Sat Aug 31 14:11:52 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(K2FeedbackReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table k2_feedback_reply
     *
     * @mbggenerated Sat Aug 31 14:11:52 CST 2019
     */
    int updateByPrimaryKey(K2FeedbackReply record);
}