package com.king2.commons.mapper;

import com.king2.commons.pojo.K2ProductCommonskus;
import com.king2.commons.pojo.K2ProductCommonskusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface K2ProductCommonskusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table k2_product_commonskus
     *
     * @mbggenerated Sun Aug 11 10:19:30 CST 2019
     */
    int countByExample(K2ProductCommonskusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table k2_product_commonskus
     *
     * @mbggenerated Sun Aug 11 10:19:30 CST 2019
     */
    int deleteByExample(K2ProductCommonskusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table k2_product_commonskus
     *
     * @mbggenerated Sun Aug 11 10:19:30 CST 2019
     */
    int deleteByPrimaryKey(Integer productCommonskusId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table k2_product_commonskus
     *
     * @mbggenerated Sun Aug 11 10:19:30 CST 2019
     */
    int insert(K2ProductCommonskus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table k2_product_commonskus
     *
     * @mbggenerated Sun Aug 11 10:19:30 CST 2019
     */
    int insertSelective(K2ProductCommonskus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table k2_product_commonskus
     *
     * @mbggenerated Sun Aug 11 10:19:30 CST 2019
     */
    List<K2ProductCommonskus> selectByExample(K2ProductCommonskusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table k2_product_commonskus
     *
     * @mbggenerated Sun Aug 11 10:19:30 CST 2019
     */
    K2ProductCommonskus selectByPrimaryKey(Integer productCommonskusId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table k2_product_commonskus
     *
     * @mbggenerated Sun Aug 11 10:19:30 CST 2019
     */
    int updateByExampleSelective(@Param("record") K2ProductCommonskus record, @Param("example") K2ProductCommonskusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table k2_product_commonskus
     *
     * @mbggenerated Sun Aug 11 10:19:30 CST 2019
     */
    int updateByExample(@Param("record") K2ProductCommonskus record, @Param("example") K2ProductCommonskusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table k2_product_commonskus
     *
     * @mbggenerated Sun Aug 11 10:19:30 CST 2019
     */
    int updateByPrimaryKeySelective(K2ProductCommonskus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table k2_product_commonskus
     *
     * @mbggenerated Sun Aug 11 10:19:30 CST 2019
     */
    int updateByPrimaryKey(K2ProductCommonskus record);
}