package com.king2.commons.mapper;

import com.king2.commons.pojo.K2RoleMember;
import com.king2.commons.pojo.K2RoleMemberExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface K2RoleMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table k2_role_member
     *
     * @mbggenerated Sun Aug 11 12:13:32 CST 2019
     */
    int countByExample(K2RoleMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table k2_role_member
     *
     * @mbggenerated Sun Aug 11 12:13:32 CST 2019
     */
    int deleteByExample(K2RoleMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table k2_role_member
     *
     * @mbggenerated Sun Aug 11 12:13:32 CST 2019
     */
    int deleteByPrimaryKey(Integer roleMemberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table k2_role_member
     *
     * @mbggenerated Sun Aug 11 12:13:32 CST 2019
     */
    int insert(K2RoleMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table k2_role_member
     *
     * @mbggenerated Sun Aug 11 12:13:32 CST 2019
     */
    int insertSelective(K2RoleMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table k2_role_member
     *
     * @mbggenerated Sun Aug 11 12:13:32 CST 2019
     */
    List<K2RoleMember> selectByExample(K2RoleMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table k2_role_member
     *
     * @mbggenerated Sun Aug 11 12:13:32 CST 2019
     */
    K2RoleMember selectByPrimaryKey(Integer roleMemberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table k2_role_member
     *
     * @mbggenerated Sun Aug 11 12:13:32 CST 2019
     */
    int updateByExampleSelective(@Param("record") K2RoleMember record, @Param("example") K2RoleMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table k2_role_member
     *
     * @mbggenerated Sun Aug 11 12:13:32 CST 2019
     */
    int updateByExample(@Param("record") K2RoleMember record, @Param("example") K2RoleMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table k2_role_member
     *
     * @mbggenerated Sun Aug 11 12:13:32 CST 2019
     */
    int updateByPrimaryKeySelective(K2RoleMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table k2_role_member
     *
     * @mbggenerated Sun Aug 11 12:13:32 CST 2019
     */
    int updateByPrimaryKey(K2RoleMember record);
}