#设置当前的端口号
server:
  port: 9999
spring:
  application:
    #设置当前的服务的名称
    name: eureka-server
  #配置安全认证才能访问eureka注册中心
  security:
    user:
      name: king2
      password: king2

    #当页面访问不到eureka页面的时候开启
#  freemarker:
#    #否优先从文件系统加载template，默认值为true
#    prefer-file-system-access: false

eureka:
  instance:
    hostname: localhost
    #不配置的话是本机的机器名注册上去  配置了的话是本机的ip地址注册上去
    #如果与这里的解释不相同有可能是多块网卡干扰了
    preferIpAddress: true
    # 心跳间隔
    lease-renewal-interval-in-seconds: 3
    # 服务失效时间： 如果多久没有收到请求，则可以删除服务
    lease-expiration-duration-in-seconds: 7
  client:
    # 关闭eureka client
    # enabled: false
    # 注册自身到eureka服务器
    register-with-eureka: false
    # 表示是否从eureka服务器获取注册信息
    fetch-registry: false
    # 客户端从Eureka Server集群里更新Eureka Server信息的频率
    eureka-service-url-poll-interval-seconds: 60
    # 定义从注册中心获取注册服务的信息
    registry-fetch-interval-seconds: 5
    # 设置eureka服务器所在的地址，查询服务和注册服务都需要依赖这个地址
    service-url:
      defaultZone: http://king2:king2@${eureka.instance.hostname}:${server.port}/eureka/
  server:
    # renewal-percent-threshold: 0.1
    # 关闭自我保护模式
    enable-self-preservation: false
    # Eureka Server 自我保护系数，当enable-self-preservation=true时，启作用
    # renewal-percent-threshold:
    # 设置清理间隔,单位为毫秒,默认为0
    eviction-interval-timer-in-ms: 3000
    # 设置如果Eureka Server启动时无法从临近Eureka Server节点获取注册信息，它多久不对外提供注册服务
    wait-time-in-ms-when-sync-empty: 6000000
    # 集群之间相互更新节点信息的时间频率
    peer-eureka-nodes-update-interval-ms: 6000


