package com.king2.commons.pojo;

import java.util.Date;

public class K2FeedbackReply {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column k2_feedback_reply.reply_id
     *
     * @mbggenerated Sat Aug 31 14:11:52 CST 2019
     */
    private Integer replyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column k2_feedback_reply.feedback_id
     *
     * @mbggenerated Sat Aug 31 14:11:52 CST 2019
     */
    private Integer feedbackId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column k2_feedback_reply.create_time
     *
     * @mbggenerated Sat Aug 31 14:11:52 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column k2_feedback_reply.retain1
     *
     * @mbggenerated Sat Aug 31 14:11:52 CST 2019
     */
    private String retain1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column k2_feedback_reply.retain2
     *
     * @mbggenerated Sat Aug 31 14:11:52 CST 2019
     */
    private String retain2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column k2_feedback_reply.retain3
     *
     * @mbggenerated Sat Aug 31 14:11:52 CST 2019
     */
    private String retain3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column k2_feedback_reply.retain4
     *
     * @mbggenerated Sat Aug 31 14:11:52 CST 2019
     */
    private String retain4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column k2_feedback_reply.retain5
     *
     * @mbggenerated Sat Aug 31 14:11:52 CST 2019
     */
    private String retain5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column k2_feedback_reply.reply_content
     *
     * @mbggenerated Sat Aug 31 14:11:52 CST 2019
     */
    private String replyContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column k2_feedback_reply.reply_id
     *
     * @return the value of k2_feedback_reply.reply_id
     *
     * @mbggenerated Sat Aug 31 14:11:52 CST 2019
     */
    public Integer getReplyId() {
        return replyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column k2_feedback_reply.reply_id
     *
     * @param replyId the value for k2_feedback_reply.reply_id
     *
     * @mbggenerated Sat Aug 31 14:11:52 CST 2019
     */
    public void setReplyId(Integer replyId) {
        this.replyId = replyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column k2_feedback_reply.feedback_id
     *
     * @return the value of k2_feedback_reply.feedback_id
     *
     * @mbggenerated Sat Aug 31 14:11:52 CST 2019
     */
    public Integer getFeedbackId() {
        return feedbackId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column k2_feedback_reply.feedback_id
     *
     * @param feedbackId the value for k2_feedback_reply.feedback_id
     *
     * @mbggenerated Sat Aug 31 14:11:52 CST 2019
     */
    public void setFeedbackId(Integer feedbackId) {
        this.feedbackId = feedbackId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column k2_feedback_reply.create_time
     *
     * @return the value of k2_feedback_reply.create_time
     *
     * @mbggenerated Sat Aug 31 14:11:52 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column k2_feedback_reply.create_time
     *
     * @param createTime the value for k2_feedback_reply.create_time
     *
     * @mbggenerated Sat Aug 31 14:11:52 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column k2_feedback_reply.retain1
     *
     * @return the value of k2_feedback_reply.retain1
     *
     * @mbggenerated Sat Aug 31 14:11:52 CST 2019
     */
    public String getRetain1() {
        return retain1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column k2_feedback_reply.retain1
     *
     * @param retain1 the value for k2_feedback_reply.retain1
     *
     * @mbggenerated Sat Aug 31 14:11:52 CST 2019
     */
    public void setRetain1(String retain1) {
        this.retain1 = retain1 == null ? null : retain1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column k2_feedback_reply.retain2
     *
     * @return the value of k2_feedback_reply.retain2
     *
     * @mbggenerated Sat Aug 31 14:11:52 CST 2019
     */
    public String getRetain2() {
        return retain2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column k2_feedback_reply.retain2
     *
     * @param retain2 the value for k2_feedback_reply.retain2
     *
     * @mbggenerated Sat Aug 31 14:11:52 CST 2019
     */
    public void setRetain2(String retain2) {
        this.retain2 = retain2 == null ? null : retain2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column k2_feedback_reply.retain3
     *
     * @return the value of k2_feedback_reply.retain3
     *
     * @mbggenerated Sat Aug 31 14:11:52 CST 2019
     */
    public String getRetain3() {
        return retain3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column k2_feedback_reply.retain3
     *
     * @param retain3 the value for k2_feedback_reply.retain3
     *
     * @mbggenerated Sat Aug 31 14:11:52 CST 2019
     */
    public void setRetain3(String retain3) {
        this.retain3 = retain3 == null ? null : retain3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column k2_feedback_reply.retain4
     *
     * @return the value of k2_feedback_reply.retain4
     *
     * @mbggenerated Sat Aug 31 14:11:52 CST 2019
     */
    public String getRetain4() {
        return retain4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column k2_feedback_reply.retain4
     *
     * @param retain4 the value for k2_feedback_reply.retain4
     *
     * @mbggenerated Sat Aug 31 14:11:52 CST 2019
     */
    public void setRetain4(String retain4) {
        this.retain4 = retain4 == null ? null : retain4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column k2_feedback_reply.retain5
     *
     * @return the value of k2_feedback_reply.retain5
     *
     * @mbggenerated Sat Aug 31 14:11:52 CST 2019
     */
    public String getRetain5() {
        return retain5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column k2_feedback_reply.retain5
     *
     * @param retain5 the value for k2_feedback_reply.retain5
     *
     * @mbggenerated Sat Aug 31 14:11:52 CST 2019
     */
    public void setRetain5(String retain5) {
        this.retain5 = retain5 == null ? null : retain5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column k2_feedback_reply.reply_content
     *
     * @return the value of k2_feedback_reply.reply_content
     *
     * @mbggenerated Sat Aug 31 14:11:52 CST 2019
     */
    public String getReplyContent() {
        return replyContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column k2_feedback_reply.reply_content
     *
     * @param replyContent the value for k2_feedback_reply.reply_content
     *
     * @mbggenerated Sat Aug 31 14:11:52 CST 2019
     */
    public void setReplyContent(String replyContent) {
        this.replyContent = replyContent == null ? null : replyContent.trim();
    }
}