package com.king2.commons.pojo;

public class K2ProductCommonskus {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column k2_product_commonskus.product_commonskus_id
     *
     * @mbggenerated Sun Aug 11 10:19:30 CST 2019
     */
    private Integer productCommonskusId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column k2_product_commonskus.commons_sku_id
     *
     * @mbggenerated Sun Aug 11 10:19:30 CST 2019
     */
    private Integer commonsSkuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column k2_product_commonskus.product_id
     *
     * @mbggenerated Sun Aug 11 10:19:30 CST 2019
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column k2_product_commonskus.retain1
     *
     * @mbggenerated Sun Aug 11 10:19:30 CST 2019
     */
    private String retain1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column k2_product_commonskus.retain2
     *
     * @mbggenerated Sun Aug 11 10:19:30 CST 2019
     */
    private String retain2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column k2_product_commonskus.retain3
     *
     * @mbggenerated Sun Aug 11 10:19:30 CST 2019
     */
    private String retain3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column k2_product_commonskus.retain4
     *
     * @mbggenerated Sun Aug 11 10:19:30 CST 2019
     */
    private String retain4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column k2_product_commonskus.retain5
     *
     * @mbggenerated Sun Aug 11 10:19:30 CST 2019
     */
    private String retain5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column k2_product_commonskus.product_commonskus_id
     *
     * @return the value of k2_product_commonskus.product_commonskus_id
     *
     * @mbggenerated Sun Aug 11 10:19:30 CST 2019
     */
    public Integer getProductCommonskusId() {
        return productCommonskusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column k2_product_commonskus.product_commonskus_id
     *
     * @param productCommonskusId the value for k2_product_commonskus.product_commonskus_id
     *
     * @mbggenerated Sun Aug 11 10:19:30 CST 2019
     */
    public void setProductCommonskusId(Integer productCommonskusId) {
        this.productCommonskusId = productCommonskusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column k2_product_commonskus.commons_sku_id
     *
     * @return the value of k2_product_commonskus.commons_sku_id
     *
     * @mbggenerated Sun Aug 11 10:19:30 CST 2019
     */
    public Integer getCommonsSkuId() {
        return commonsSkuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column k2_product_commonskus.commons_sku_id
     *
     * @param commonsSkuId the value for k2_product_commonskus.commons_sku_id
     *
     * @mbggenerated Sun Aug 11 10:19:30 CST 2019
     */
    public void setCommonsSkuId(Integer commonsSkuId) {
        this.commonsSkuId = commonsSkuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column k2_product_commonskus.product_id
     *
     * @return the value of k2_product_commonskus.product_id
     *
     * @mbggenerated Sun Aug 11 10:19:30 CST 2019
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column k2_product_commonskus.product_id
     *
     * @param productId the value for k2_product_commonskus.product_id
     *
     * @mbggenerated Sun Aug 11 10:19:30 CST 2019
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column k2_product_commonskus.retain1
     *
     * @return the value of k2_product_commonskus.retain1
     *
     * @mbggenerated Sun Aug 11 10:19:30 CST 2019
     */
    public String getRetain1() {
        return retain1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column k2_product_commonskus.retain1
     *
     * @param retain1 the value for k2_product_commonskus.retain1
     *
     * @mbggenerated Sun Aug 11 10:19:30 CST 2019
     */
    public void setRetain1(String retain1) {
        this.retain1 = retain1 == null ? null : retain1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column k2_product_commonskus.retain2
     *
     * @return the value of k2_product_commonskus.retain2
     *
     * @mbggenerated Sun Aug 11 10:19:30 CST 2019
     */
    public String getRetain2() {
        return retain2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column k2_product_commonskus.retain2
     *
     * @param retain2 the value for k2_product_commonskus.retain2
     *
     * @mbggenerated Sun Aug 11 10:19:30 CST 2019
     */
    public void setRetain2(String retain2) {
        this.retain2 = retain2 == null ? null : retain2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column k2_product_commonskus.retain3
     *
     * @return the value of k2_product_commonskus.retain3
     *
     * @mbggenerated Sun Aug 11 10:19:30 CST 2019
     */
    public String getRetain3() {
        return retain3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column k2_product_commonskus.retain3
     *
     * @param retain3 the value for k2_product_commonskus.retain3
     *
     * @mbggenerated Sun Aug 11 10:19:30 CST 2019
     */
    public void setRetain3(String retain3) {
        this.retain3 = retain3 == null ? null : retain3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column k2_product_commonskus.retain4
     *
     * @return the value of k2_product_commonskus.retain4
     *
     * @mbggenerated Sun Aug 11 10:19:30 CST 2019
     */
    public String getRetain4() {
        return retain4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column k2_product_commonskus.retain4
     *
     * @param retain4 the value for k2_product_commonskus.retain4
     *
     * @mbggenerated Sun Aug 11 10:19:30 CST 2019
     */
    public void setRetain4(String retain4) {
        this.retain4 = retain4 == null ? null : retain4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column k2_product_commonskus.retain5
     *
     * @return the value of k2_product_commonskus.retain5
     *
     * @mbggenerated Sun Aug 11 10:19:30 CST 2019
     */
    public String getRetain5() {
        return retain5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column k2_product_commonskus.retain5
     *
     * @param retain5 the value for k2_product_commonskus.retain5
     *
     * @mbggenerated Sun Aug 11 10:19:30 CST 2019
     */
    public void setRetain5(String retain5) {
        this.retain5 = retain5 == null ? null : retain5.trim();
    }
}