package com.king2.commons.pojo;

public class K2RoleMember {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column k2_role_member.role_member_id
     *
     * @mbggenerated Sun Aug 11 12:13:32 CST 2019
     */
    private Integer roleMemberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column k2_role_member.role_id
     *
     * @mbggenerated Sun Aug 11 12:13:32 CST 2019
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column k2_role_member.member_id
     *
     * @mbggenerated Sun Aug 11 12:13:32 CST 2019
     */
    private Integer memberId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column k2_role_member.role_member_id
     *
     * @return the value of k2_role_member.role_member_id
     *
     * @mbggenerated Sun Aug 11 12:13:32 CST 2019
     */
    public Integer getRoleMemberId() {
        return roleMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column k2_role_member.role_member_id
     *
     * @param roleMemberId the value for k2_role_member.role_member_id
     *
     * @mbggenerated Sun Aug 11 12:13:32 CST 2019
     */
    public void setRoleMemberId(Integer roleMemberId) {
        this.roleMemberId = roleMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column k2_role_member.role_id
     *
     * @return the value of k2_role_member.role_id
     *
     * @mbggenerated Sun Aug 11 12:13:32 CST 2019
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column k2_role_member.role_id
     *
     * @param roleId the value for k2_role_member.role_id
     *
     * @mbggenerated Sun Aug 11 12:13:32 CST 2019
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column k2_role_member.member_id
     *
     * @return the value of k2_role_member.member_id
     *
     * @mbggenerated Sun Aug 11 12:13:32 CST 2019
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column k2_role_member.member_id
     *
     * @param memberId the value for k2_role_member.member_id
     *
     * @mbggenerated Sun Aug 11 12:13:32 CST 2019
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }
}