package com.king2.commons.pojo;

public class King2SensitivityLexicon {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column king2_sensitivity_lexicon.lexicon_id
     *
     * @mbggenerated Sat Aug 17 09:38:13 CST 2019
     */
    private Integer lexiconId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column king2_sensitivity_lexicon.lexicon_content
     *
     * @mbggenerated Sat Aug 17 09:38:13 CST 2019
     */
    private String lexiconContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column king2_sensitivity_lexicon.lexicon_id
     *
     * @return the value of king2_sensitivity_lexicon.lexicon_id
     *
     * @mbggenerated Sat Aug 17 09:38:13 CST 2019
     */
    public Integer getLexiconId() {
        return lexiconId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column king2_sensitivity_lexicon.lexicon_id
     *
     * @param lexiconId the value for king2_sensitivity_lexicon.lexicon_id
     *
     * @mbggenerated Sat Aug 17 09:38:13 CST 2019
     */
    public void setLexiconId(Integer lexiconId) {
        this.lexiconId = lexiconId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column king2_sensitivity_lexicon.lexicon_content
     *
     * @return the value of king2_sensitivity_lexicon.lexicon_content
     *
     * @mbggenerated Sat Aug 17 09:38:13 CST 2019
     */
    public String getLexiconContent() {
        return lexiconContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column king2_sensitivity_lexicon.lexicon_content
     *
     * @param lexiconContent the value for king2_sensitivity_lexicon.lexicon_content
     *
     * @mbggenerated Sat Aug 17 09:38:13 CST 2019
     */
    public void setLexiconContent(String lexiconContent) {
        this.lexiconContent = lexiconContent == null ? null : lexiconContent.trim();
    }
}