#设置当前的端口号
server:
  port: 9999
spring:
  application:
    #设置当前的服务的名称
    name: eureka-server
  #配置安全认证才能访问eureka注册中心
  security:
    user:
      name: king2
      password: king2

    #当页面访问不到eureka页面的时候开启
#  freemarker:
#    #否优先从文件系统加载template，默认值为true
#    prefer-file-system-access: false

eureka:
  instance:
    hostname: localhost
    #不配置的话是本机的机器名注册上去  配置了的话是本机的ip地址注册上去
    #如果与这里的解释不相同有可能是多块网卡干扰了
    preferIpAddress: true

    # 心跳机制每三秒向服务端发送健康情况
    lease-renewal-interval-in-seconds: 3
    # 当心跳停止过7秒后就可以让服务中心那边按规定时间清楚无效的服务
    lease-expiration-duration-in-seconds: 7
  client:
    # 开启健康检查 （依赖spring-boot-starter-actuator）
    healthcheck:
      enabled: true

    # 关闭eureka client
    # enabled: false

    # 注册自身到eureka服务器 由于当前是服务无效将自己注册上去
    register-with-eureka: false
    # 表示是否从eureka服务器获取注册信息
    fetch-registry: false

    # 设置eureka服务器所在的地址，查询服务和注册服务都需要依赖这个地址
    service-url:
      defaultZone: http://king2:king2@${eureka.instance.hostname}:${server.port}/eureka/

  server:
    # renewal-percent-threshold: 0.1
    # 关闭自我保护模式   开启的作用：当服务与注册中心由于某个原因断开的时候，服务与服务之间还可以连接，这时候eureka不会立刻清理，依旧会对改微服的信息进行保存。
    enable-self-preservation: false

    # 设置清理无效服务间隔 3秒清理一次
    eviction-interval-timer-in-ms: 3000

    # 集群之间相互更新节点信息的时间频率
    #peer-eureka-nodes-update-interval-ms: 6000


